#PowerShell command : [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("alex:password"))

###GET ALL PRODUCTS
GET http://localhost:8080/api/products
#Base Authentication Header
Authorization: Basic YWxleDpwYXNzd29yZA==
Content-Type: application/json

{}


###GET PRODUCT BY ID
GET http://localhost:8080/api/products/1
Authorization: Basic YWxleDpwYXNzd29yZA==
Content-Type: application/json

###POST PRODUCT
POST http://localhost:8080/api/products
Authorization: Basic YWxleDpwYXNzd29yZA==
Content-Type: application/json

{
  "name": "Product Created",
  "price": "100.00"
}


###POST REGISTER USER
POST http://localhost:8080/api/auth/register
Content-type: application/json

{
  "fullName": "Alex Black",
  "username": "alex",
  "password": "password",
  "role": "ROLE_ADMIN"
}


###POST LOGIN USER
POST http://localhost:8080/api/auth/login
Content-type: application/json

{
  "username": "alex",
  "password": "password"
}

###GET ALL PRODUCTS
GET http://localhost:8080/api/products
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJNSzVTVWtveVlSN3R3Y3dqdTFjNEVkVEZub0tOYk9NVG9CUWo4NjdobUp6cGVZYlRxMUJPb3QxaDU0SDB4ZnkyIiwic3ViIjoiYWxleCIsInRva2VuVHlwZSI6ImFjY2Vzc1Rva2VuIiwiaWF0IjoxNzUwNDUxODEwLCJleHAiOjE3NTA0NTU0MTB9._A7tz47NyEwXpQ42GHfkoPGhKlB1ySwcEXyoDSAZVUsa1hFz3lVKKlbQIhVLGWrG7rJb8CLr30eiDuFefaay7A
Content-Type: application/json

{}


###Authorization: Bearer